name: Compile pthread-win32 as static library
run-name: Compile pthread-win32 - ${{ github.sha }}
on: push
jobs:
  compile:
    strategy:
      matrix:
        arch: [x86, x64]
    name: Compile pthread-win32
    runs-on: windows-latest
    steps:
      - name: Compile
        continue-on-error: true
        run: |
          Import-Module 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\Microsoft.VisualStudio.DevShell.dll'
          Enter-VsDevShell -VsInstallPath 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise' -DevCmdArguments '-arch=${{ matrix.arch }}' -StartInPath 'C:\'
          git clone https://github.com/GerHobbelt/pthread-win32.git
          cd C:\pthread-win32\windows\VS2022
          msbuild .\pthread.2022.sln -t:pthread_static_lib -p:Configuration=Release,Platform=${{ matrix.arch }}
          cd C:\
          mkdir C:\artifacts
          mkdir C:\artifacts\include
          mkdir C:\artifacts\lib
          cp C:\pthread-win32\windows\VS2022\bin\Release-Unicode-64bit-${{ matrix.arch }}\pthread_static_lib.lib C:\artifacts\lib\pthread.lib
          cp C:\pthread-win32\_ptw32.h C:\artifacts\include
          cp C:\pthread-win32\pthread.h C:\artifacts\include
          cp C:\pthread-win32\sched.h C:\artifacts\include
          cp C:\pthread-win32\semaphore.h C:\artifacts\include

      - name: Check
        run: |
          ls C:\artifacts\include
          ls C:\artifacts\lib

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          path: C:\artifacts
