name: Compile pthread-win32 as static library
run-name: Compile pthread-win32 - ${{ github.sha }}
on: workflow_dispatch
jobs:
  compile:
    name: Compile pthread-win32
    runs-on: windows-latest
    steps:
      - name: Compile
        continue-on-error: true
        run: |
          Import-Module 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\Microsoft.VisualStudio.DevShell.dll'
          Enter-VsDevShell -VsInstallPath 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise' -DevCmdArguments '-arch=x64' -StartInPath 'C:\'
          git clone https://github.com/GerHobbelt/pthread-win32.git
          cd C:\pthread-win32\windows\VS2022
          msbuild .\pthread.2022.sln -t:pthread_static_lib -p:Configuration=Release,Platform=x64
          cd C:\
          mkdir C:\artifacts
          mkdir C:\artifacts\include
          mkdir C:\artifacts\lib
          cp C:\pthread-win32\windows\VS2022\bin\Release-Unicode-64bit-x64\pthread_static_lib.lib C:\artifacts\lib
          cp C:\pthread-win32\_ptw32.h C:\artifacts\include
          cp C:\pthread-win32\pthread.h C:\artifacts\include
          cp C:\pthread-win32\sched.h C:\artifacts\include
          cp C:\pthread-win32\semaphore.h C:\artifacts\include

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          path: C:\artifacts